{{ config(materialized='table') }}

SELECT
    ID_LIGNE,
    ID_COMMANDE,
    DATE_DE_COMMANDE,
    DATE_D_EXPEDITION,
    ID_CLIENT,
    ID_PRODUIT,
    MONTANT_DES_VENTES,
    QUANTITE,
    REMISE,
    PROFIT,
    STATUT_COMMANDE,
    VILLE AS ID_VILLE
FROM {{ source('GOOGLE_DRIVE_TD', 'EXEMPLE_HYPERMARCHE_ACHATS') }}